# Generated by Django 3.1.7 on 2021-05-06 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_auth', '0003_auto_20210506_0553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
