# Generated by Django 3.1.7 on 2021-05-06 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_auth', '0004_remove_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
