# Generated by Django 3.1.7 on 2021-05-05 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel_1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TestModel_2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_app.testmodel_1')),
            ],
        ),
    ]
