# Generated by Django 3.1.7 on 2021-05-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel_1',
            name='v',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testmodel_2',
            name='v',
            field=models.IntegerField(default=0),
        ),
    ]
