# Generated by Django 3.1.7 on 2021-05-04 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0002_auto_20210504_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='id',
            new_name='addressId',
        ),
    ]
