# Generated by Django 3.1.7 on 2021-05-04 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0004_auto_20210504_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomNumber',
            field=models.SmallIntegerField(),
        ),
    ]
