# Generated by Django 3.1.7 on 2021-05-05 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sms_app', '0005_auto_20210504_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='roomId',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='bookingId',
            new_name='booking',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customerInfoId',
            new_name='customerInfo',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='tcId',
            new_name='tc',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='postId',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='sanatoriumId',
            new_name='sanatorium',
        ),
        migrations.RenameField(
            model_name='sanatorium',
            old_name='addressId',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='userId',
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
