# Generated by Django 3.1.7 on 2021-05-05 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0006_auto_20210504_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='sanatorium',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sms_app.sanatorium'),
        ),
    ]
