# Generated by Django 3.1.7 on 2021-05-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0008_auto_20210505_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='payed',
            field=models.BooleanField(default=False),
        ),
    ]
