# Generated by Django 3.1.7 on 2021-05-06 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0009_auto_20210506_0533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='addedBy',
        ),
    ]
