# Generated by Django 3.1.7 on 2021-05-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0011_booking_addedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='buildingCorpse',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
