# Generated by Django 3.1.7 on 2021-05-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0012_auto_20210506_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
